name: Docs
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: deploy
  cancel-in-progress: false
jobs:
  build:
    name: doc-x86_64-pc-windows-msvc
    runs-on: windows-latest
    steps:
      - name: disable git eol translation
        run: git config --global core.autocrlf false

      - name: checkout
        uses: actions/checkout@v4

      - name: Install Rustup using win.rustup.rs
        run: |
          # Disable the download progress bar which can cause perf issues
          $ProgressPreference = "SilentlyContinue"
          Invoke-WebRequest https://win.rustup.rs/ -OutFile rustup-init.exe
          .\rustup-init.exe -y --default-host=x86_64-pc-windows-msvc --default-toolchain=none
          del rustup-init.exe
          rustup target add x86_64-pc-windows-msvc
        shell: powershell

      - name: Build and Test
        shell: cmd
        run: ci\build_and_test.bat

      - name: Setup pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Clean docs folder
        run: cargo clean --doc

      - name: Build docs
        run: cargo doc --no-deps

      - name: Add redirect
        run: Set-Content -Path "target/doc/index.html" -Value '<meta http-equiv="refresh" content="0;url=renga_api_rs/index.html">'

      - name: Remove lock file
        run: Remove-Item -Path "target/doc/.lock"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc
  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4